# -*- coding: utf-8 -*-
"""Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IXGwkoNrT3IqBh3G-W63psWkBnoymofo

# **Logistic** **Regression**
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

data = pd.read_csv("heartfailure.csv")


data.head()

X = data.drop("DEATH_EVENT", axis=1)
y = data["DEATH_EVENT"]

X.shape

y.shape

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.4, random_state=0
)

X_train.shape

X_test.shape

model = LogisticRegression()

model.fit(X_train,y_train)

y_predict = model.predict(X_test)

accuracy = accuracy_score(y_test, y_predict)

print("Accuracy: ",accuracy)

"""# **Decision** **Tree**"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

data = pd.read_csv("heartfailure.csv")

data.head()

X = data.drop("DEATH_EVENT", axis=1)
y = data["DEATH_EVENT"]

X.shape

y.shape

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.4, random_state=0
)

X_train.shape

X_test.shape

model1 = DecisionTreeClassifier()

model1.fit(X_train,y_train)

y_predict = model1.predict(X_test)

accuracy = accuracy_score(y_test, y_predict)

print("Accuracy: ",accuracy)

"""# **Random** **Forest**"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4)

model2 = RandomForestClassifier()

model2.fit(X_train, y_train)

y_predict = model2.predict(X_test)

accuracy = accuracy_score(y_test, y_predict)

print("Accuracy: ",accuracy)
